### ISSUE TITLE
Issue with conflicting packages

### ISSUE THREAD

**Issue by tawbery** [DOI-USGS/hyRefactor#53]
Hi,

Apologies for my naivety/ignorance this is my first time writing one of these and I'm not sure what form they take.
I was having  a problem running this code due to package conflicts. I am afraid I am too new at R to tell you what package makes this conflict arise.

If you change `select` to `dplyr::select` then it solves the conflict. 
Note this is mainly done but a couple are left just as select.

Hope this helps.

**Comment by dblodgett-usgs** [comment]
Hi there -- Do you have a reprex for this? 

Most likely just doing `library(dplyr)` before calling the package functions should also fix the issue?

hyRefactor is not really being maintained anymore. We've moved all this functionality into https://github.com/mikejohnson51/hydrofab (soon to be under noaa-owp/hydrofab)
